#
#  Handlebars Variables
#

site:
    title:          Rico A. Beti | Software Enthusiast
    url:            https://ricobeti.ch
    description:    Rico A. Beti, Software Enthusiast, Personal Portfolio.
    brand:          RB

    theme:
        primary:    3465A4
        colors:     blue-grey darken-2
        accent:     blue-grey

    social:
        twitter:    https://twitter.com/RicoBeti
        linkedin:   https://www.linkedin.com/in/ricobeti/
        github:     https://github.com/SilentByte
        email:      mailto:rico@beti.ch

    sections:
        - template: navigation

        - template: about
          name:     about
          title:    About

        - template: portfolio
          name:     portfolio
          title:    Portfolio

        - template: contact
          name:     contact
          title:    Contact

        - template: footer

