#
#  Handlebars Variables
#

site:
    title:          Rico A. Beti | Software Enthusiast
    url:            https://ricobeti.ch
    description:    Rico A. Beti, Software Enthusiast, Personal Portfolio.
    brand:          RB

    theme:
        primary:        3465A4
        colors:         blue-grey darken-2
        accent:         blue-grey

    social:
        twitter:        https://twitter.com/RicoBeti
        linkedin:       https://www.linkedin.com/in/ricobeti/
        github:         https://github.com/SilentByte
        email:          mailto:rico@beti.ch

    sections:
        navigation:

        about:
            name:       about
            title:      About
            headings:
                        - ^500 Hi, I'm <span class="blue-grey-text">Rico</span>.^800
                        - ^500 I <i class="fa fa-heart blue-grey-text" aria-hidden="true"></i> Coding!^800
                        - ^500 This is my <span class="blue-grey-text">online</span> portfolio.^800
                        - ^500 Rico A. Beti
            text: >
                        I'm a passionate software engineer of Swiss origin
                        living and studying in Perth, WA.

        portfolio:
            name:       portfolio
            title:      Portfolio

        contact:
            name:       contact
            title:      Contact

        footer:

