#
#  Handlebars Variables
#

site:
    title:          Rico A. Beti
    url:            https://ricobeti.ch
    description:    Personal Portfolio.
    brand:          RB
    theme:          3465A4

    sections:
        - name:     about
          title:    About
        - name:     portfolio
          title:    Portfolio
        - name:     contact
          title:    Contact

