#
#  Handlebars Variables
#

site:
    title:          Rico A. Beti
    url:            https://ricobeti.ch
    description:    Personal Portfolio.
    brand:          RB
    theme:          3465A4
    colors:         blue-grey darken-2
    accent:         blue-grey

    social:
        twitter:    https://twitter.com/RicoBeti
        linkedin:   https://www.linkedin.com/in/ricobeti/
        github:     https://github.com/SilentByte
        email:      mailto:rico@beti.ch

    sections:
        - name:     about
          title:    About
        - name:     portfolio
          title:    Portfolio
        - name:     contact
          title:    Contact

